version: '3'
services:
  user-service:
    container_name: api
    build: ./user-service
    ports:
      - 3001:3001
  book-service:
    container_name: book
    build: ./book-service
    ports:
      - 3002:3002
  order-service:
    container_name: order
    build: ./order-service
    ports:
      - 3003:3003
  review-service:
    container_name: review
    build: ./review-service
    ports:
      - 3004:3004
  kong-database:
    container_name: kong-database
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
  kong:
    container_name: kong
    image: book-kong:latest
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    entrypoint: /kong-entrypoint.sh
    command: docker-start
    ports:
      - '80:80'
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
    volumes:
      - ./kong-entrypoint.sh:/kong-entrypoint.sh
      - ./wait-for-it.sh:/wait-for-it.sh
      - ./setup-kong.sh:/setup-kong.sh
      - ./descriptor.proto:/proto/descriptor.proto
      - ./annotations.proto:/proto/annotations.proto
      - ./http.proto:/proto/http.proto
      - ./book-service/proto/book.proto:/proto/book.proto
      - ./order-service/proto/order.proto:/proto/order.proto
      - ./review-service/proto/review.proto:/proto/review.proto
      - ./user-service/proto/user.proto:/proto/api.proto